// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx1k0fKJYC2L1PY7ouPvV91lfw8d-5F4',
    appId: '1:648822028461:web:35c5462fd49632c9ceee24',
    messagingSenderId: '648822028461',
    projectId: 'moza-972f4',
    authDomain: 'moza-972f4.firebaseapp.com',
    storageBucket: 'moza-972f4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrlUyZ7Oy0HK83H_FGvAC-95qSkF3_u-E',
    appId: '1:648822028461:android:950e2f193152715dceee24',
    messagingSenderId: '648822028461',
    projectId: 'moza-972f4',
    storageBucket: 'moza-972f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjdTICc3TocR5ovV2dtSUyLewsbUOerDY',
    appId: '1:648822028461:ios:d0a2a5610780a6cfceee24',
    messagingSenderId: '648822028461',
    projectId: 'moza-972f4',
    storageBucket: 'moza-972f4.firebasestorage.app',
    iosClientId: '648822028461-tkq1hd1n1ikjft774h1ltvjfqchtn6m8.apps.googleusercontent.com',
    iosBundleId: 'com.example.moza',
  );
}